//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akusticheskaya_system
    {
        public int Id_ak_sys { get; set; }
        public string Serial_number_ak_syst { get; set; }
        public string Type_oborudovaniya { get; set; }
        public string Nazvanie { get; set; }
        public Nullable<int> Max_power { get; set; }
        public string Zvukovaya_shema { get; set; }
        public int Item_Id { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
