//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        public int Id_comp { get; set; }
        public string Serial_number_pc { get; set; }
        public string Type_oborudovaniya { get; set; }
        public string Nazvanie { get; set; }
        public string Processor { get; set; }
        public string Operativnaya_pamyt { get; set; }
        public string Hard_drive { get; set; }
        public string SolidStateDrive { get; set; }
        public string Videokarta { get; set; }
        public string OC { get; set; }
        public int Item_Id { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
