//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouse
    {
        public int Id_mouse { get; set; }
        public string Serial_number_mouse { get; set; }
        public string Type_oborudovaniya { get; set; }
        public string Nazvanie { get; set; }
        public string Type_soedineniya { get; set; }
        public string Interface_mouse { get; set; }
        public int Max_razreshenie_datchika { get; set; }
        public int Item_Id { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
