//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proector
    {
        public int Id_proector { get; set; }
        public string Serial_number_proector { get; set; }
        public string Type_oborudovaniya { get; set; }
        public string Nazvanie { get; set; }
        public string Razreshenie { get; set; }
        public Nullable<int> Pikovaya_yarkost { get; set; }
        public string Sootnoshenie_storon_ekrana { get; set; }
        public int Item_Id { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
