//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scaner
    {
        public int Id_scaner { get; set; }
        public string Serial_number_scaner { get; set; }
        public string Type_oborudovaniya { get; set; }
        public string Nazvanie { get; set; }
        public string Type_skanera { get; set; }
        public string Dvustoron_scan { get; set; }
        public string Max_format_originala { get; set; }
        public int Item_Id { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
