//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sklad()
        {
            this.Akusticheskaya_system = new HashSet<Akusticheskaya_system>();
            this.Computers = new HashSet<Computers>();
            this.Klaviatura = new HashSet<Klaviatura>();
            this.Monitor = new HashSet<Monitor>();
            this.Mouse = new HashSet<Mouse>();
            this.Printer = new HashSet<Printer>();
            this.Proector = new HashSet<Proector>();
            this.Scaner = new HashSet<Scaner>();
        }
    
        public int ID_item { get; set; }
        public string Invent_num { get; set; }
        public string Ser_num { get; set; }
        public string Type_oborudovaniya_ { get; set; }
        public string Nazvanie_ob { get; set; }
        public string Mesto_Hraneniya { get; set; }
        public string Login { get; set; }
        public string Building { get; set; }
        public int Emp_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Akusticheskaya_system> Akusticheskaya_system { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Computers> Computers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klaviatura> Klaviatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monitor> Monitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mouse> Mouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Printer> Printer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proector> Proector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scaner> Scaner { get; set; }
    }
}
